# Generated by Django 5.1 on 2024-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainpageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('backHeader', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
