# Generated by Django 5.1 on 2024-08-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_modelguidebook_remove_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainpageOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('backHeader', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainpageWorkpacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('backHeader', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
