# Generated by Django 5.1 on 2024-08-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mainpagenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainpageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('backHeader', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slides/img')),
                ('description', models.TextField()),
            ],
        ),
    ]
