# Generated by Django 5.1 on 2024-08-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_mainpageview_modelview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainpageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='videos/img')),
                ('URL', models.URLField(max_length=150)),
            ],
        ),
    ]
