# Generated by Django 5.1 on 2024-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_modelnavbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelguidebook',
            name='description',
        ),
        migrations.AddField(
            model_name='modelguidebook',
            name='file',
            field=models.FileField(default=1, upload_to='documents/workpackets/pdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelnavbar',
            name='title',
            field=models.CharField(help_text="Please just enter one of these words: 'home, about, output, workpackage, news, partner, view, contact'.", max_length=100),
        ),
    ]
