# Generated by Django 5.1 on 2024-08-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_modelguidebook_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide',
            new_name='MainpageSlide',
        ),
        migrations.RenameModel(
            old_name='Gallery',
            new_name='ModelGallery',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='ModelNews',
        ),
        migrations.RenameModel(
            old_name='Partner',
            new_name='ModelPartner',
        ),
        migrations.RenameModel(
            old_name='Podcast',
            new_name='ModelPodcast',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='ModelVideo',
        ),
    ]
