# Generated by Django 5.1 on 2024-08-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_slide_mainpageslide_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelView',
        ),
    ]
