# Generated by Django 5.1 on 2024-08-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_modelview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='ModelView',
        ),
    ]
