# Generated by Django 5.1 on 2024-09-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=150)),
            ],
        ),
    ]
