# Generated by Django 5.1 on 2024-09-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_facebooklink_instagramlink_spotifylink_youtubelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
