# Generated by Django 5.1 on 2024-09-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delete_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpacket',
            name='numberpacket',
        ),
        migrations.AlterField(
            model_name='modelnavbar',
            name='title',
            field=models.CharField(help_text="Please just enter one of these words and follow this order: 'home, about, outputs, workpackages, news, partners, views, contact'.", max_length=100),
        ),
        migrations.DeleteModel(
            name='NumberWorkPacket',
        ),
        migrations.DeleteModel(
            name='WorkPacket',
        ),
    ]
