# Generated by Django 5.1 on 2024-09-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_workpacket_numberpacket_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramLink',
            new_name='LinkFacebook',
        ),
        migrations.RenameModel(
            old_name='FacebookLink',
            new_name='LinkInstagram',
        ),
        migrations.RenameModel(
            old_name='YoutubeLink',
            new_name='LinkSpotify',
        ),
        migrations.RenameModel(
            old_name='SpotifyLink',
            new_name='LinkYoutube',
        ),
    ]
