# Generated by Django 5.1 on 2024-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_instagramlink_linkfacebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageslide',
            name='image',
            field=models.ImageField(help_text="Image size should be '1920x1080'.", upload_to='slides/img'),
        ),
        migrations.AlterField(
            model_name='modelguidebook',
            name='image',
            field=models.ImageField(help_text="Image size should be '280x326'", upload_to=''),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='image',
            field=models.ImageField(help_text="Image size should be '420x316'", upload_to='news/img'),
        ),
        migrations.AlterField(
            model_name='modelpartner',
            name='image',
            field=models.ImageField(help_text="Image size should be '280x326'", upload_to='partners/img'),
        ),
    ]
