# Generated by Django 5.1 on 2024-09-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_mainpageslide_image_alter_modelguidebook_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainpageWorkpacket',
            new_name='MainpageWorkpackage',
        ),
        migrations.RenameModel(
            old_name='ModelWorkPacket',
            new_name='ModelWorkPackage',
        ),
    ]
