# Generated by Django 5.1 on 2024-09-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_mainpageworkpacket_mainpageworkpackage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainpageWorkpackage',
            new_name='MainpageWorkpacket',
        ),
        migrations.RenameModel(
            old_name='ModelWorkPackage',
            new_name='ModelWorkPacket',
        ),
    ]
