# Generated by Django 5.1 on 2024-09-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_mainpageworkpackage_mainpageworkpacket_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainpageWorkpacket',
            new_name='MainpageWorkpackaget',
        ),
        migrations.RenameModel(
            old_name='ModelWorkPacket',
            new_name='ModelWorkpackage',
        ),
    ]
