# Generated by Django 5.1 on 2024-09-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_mainpageworkpacket_mainpageworkpackaget_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainpageWorkpackaget',
            new_name='MainpageWorkpackage',
        ),
    ]
