# Generated by Django 5.1 on 2024-09-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_mainpageworkpackaget_mainpageworkpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainpageOutputContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('info', 'Info'), ('podcast', 'Podcast'), ('guidebook', 'Guidebook')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, help_text="NOTE: Image just needs for video and size should be '1920x1080'.", null=True, upload_to='videos/img')),
                ('URL', models.URLField(blank=True, help_text='NOTE: URL just needs for video.', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainpageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('slide', 'Slide Section'), ('about', 'About Section'), ('output', 'Output Section'), ('workpackage', 'Workpackage Section'), ('news', 'News Section'), ('view', 'View Section')], max_length=20)),
                ('header', models.CharField(max_length=100)),
                ('backHeader', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, help_text="NOTE: This area just for Slide part. Image size should be '1920x1080'.", null=True, upload_to='slides/img')),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('spotify', 'Spotify'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('discord', 'Discord')], max_length=20)),
                ('URL', models.URLField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='LinkFacebook',
        ),
        migrations.DeleteModel(
            name='LinkInstagram',
        ),
        migrations.DeleteModel(
            name='LinkSpotify',
        ),
        migrations.DeleteModel(
            name='LinkYoutube',
        ),
        migrations.DeleteModel(
            name='MainpageAbout',
        ),
        migrations.DeleteModel(
            name='MainpageGuidebook',
        ),
        migrations.DeleteModel(
            name='MainpageInfo',
        ),
        migrations.DeleteModel(
            name='MainpageNews',
        ),
        migrations.DeleteModel(
            name='MainpageOutput',
        ),
        migrations.DeleteModel(
            name='MainpagePodcast',
        ),
        migrations.DeleteModel(
            name='MainpageSlide',
        ),
        migrations.DeleteModel(
            name='MainpageVideo',
        ),
        migrations.DeleteModel(
            name='MainpageView',
        ),
        migrations.DeleteModel(
            name='MainpageWorkpackage',
        ),
    ]
