# Generated by Django 5.1 on 2024-09-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_mainpageworkpackaget_mainpageworkpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkDiscord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LinkTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=150)),
            ],
        ),
    ]
