# Generated by Django 5.1 on 2024-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_mainpageoutputcontent_mainpagesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text="Image size should be '1920x1080'.", upload_to='slides/img')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mainpagesection',
            name='image',
        ),
        migrations.AlterField(
            model_name='mainpagesection',
            name='section_type',
            field=models.CharField(choices=[('about', 'About Section'), ('output', 'Output Section'), ('workpackage', 'Workpackage Section'), ('news', 'News Section'), ('view', 'View Section')], max_length=20),
        ),
    ]
