# Generated by Django 5.1 on 2024-09-24 22:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_slide_remove_mainpagesection_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Image size should be relevant to content type', upload_to='content/img')),
                ('file', models.FileField(blank=True, null=True, upload_to='content/files')),
                ('URL', models.URLField(blank=True, max_length=150, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content_type', models.CharField(choices=[('news', 'News'), ('podcast', 'Podcast'), ('video', 'Video'), ('workpackage', 'Workpackage'), ('gallery', 'Gallery')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModelEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='entity/img')),
                ('website', models.URLField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('partner', 'Partner'), ('view', 'View')], max_length=20)),
            ],
        ),
    ]
