# Generated by Django 5.1 on 2024-09-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_modelcontent_modelentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelGallery',
        ),
        migrations.DeleteModel(
            name='ModelGuidebook',
        ),
        migrations.DeleteModel(
            name='ModelNews',
        ),
        migrations.DeleteModel(
            name='ModelPartner',
        ),
        migrations.DeleteModel(
            name='ModelPodcast',
        ),
        migrations.DeleteModel(
            name='ModelVideo',
        ),
        migrations.DeleteModel(
            name='ModelView',
        ),
        migrations.DeleteModel(
            name='ModelWorkpackage',
        ),
    ]
