# Generated by Django 5.1 on 2024-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_delete_modelgallery_delete_modelguidebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelentity',
            name='fullname',
            field=models.CharField(default=1, help_text='NOTE: Partners and Viewers name.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelcontent',
            name='content_type',
            field=models.CharField(choices=[('news', 'News'), ('podcast', 'Podcast'), ('video', 'Video'), ('workpackage', 'Workpackage'), ('gallery', 'Gallery'), ('guidebook', 'Guidebook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modelcontent',
            name='file',
            field=models.FileField(blank=True, help_text='NOTE: file just needs for guidebooks.', null=True, upload_to='content/files'),
        ),
        migrations.AlterField(
            model_name='modelentity',
            name='title',
            field=models.CharField(blank=True, help_text='NOTE: Just for the viws.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelentity',
            name='website',
            field=models.URLField(blank=True, help_text='NOTE: website just needs for partners.', max_length=150, null=True),
        ),
    ]
