# Generated by Django 5.1 on 2024-09-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_modelentity_fullname_alter_modelcontent_content_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelContent',
            new_name='Content',
        ),
        migrations.RenameModel(
            old_name='ModelNavbar',
            new_name='Navbar',
        ),
        migrations.RenameModel(
            old_name='ModelEntity',
            new_name='PartnerAndView',
        ),
    ]
