# Generated by Django 5.1 on 2024-10-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_modelcontent_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
