# Generated by Django 5.1 on 2024-10-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_delete_navbar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainpageOutputContent',
            new_name='OutputContent',
        ),
    ]
