# Generated by Django 5.1 on 2024-12-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_rename_mainpageoutputcontent_outputcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('news', 'News'), ('podcast', 'Podcast'), ('video', 'Video'), ('workpackage', 'Workpackage'), ('gallery', 'Gallery'), ('guidebook', 'Guidebook'), ('rturk', 'Rturk')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outputcontent',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('info', 'Info'), ('podcast', 'Podcast'), ('guidebook', 'Guidebook'), ('rturk', 'Rturk')], max_length=50),
        ),
    ]
